### ISSUE TITLE
Mocha not spawned due to long argument list?

### ISSUE THREAD

**Issue by jvanoostveen** [sindresorhus/gulp-mocha#154]
With version 4, when trying to use gulp-mocha, I'm getting
```
 UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error in plugin 'gulp-mocha'
Message:
    spawn ENAMETOOLONG
Details:
    code: ENAMETOOLONG
    errno: ENAMETOOLONG
    syscall: spawn
```

It seems this is related to the passing of the files argument, which is quite large in our case (500+ entries).

Environment: Windows 10
